[package]
name = "el"
version = "0.0.2"
edition = "2021"

[[bin]]
name = "filter"
path = "src/filter.rs"

[[bin]]
name = "delete"
path = "src/delete.rs"

[dependencies]
csv = "1.3.0"
serde = { version = "1.0.201", features = ["derive"] }
